=== kivra/developer.kivra.com/receipt/schemas/json/prescription/v1.0/prescription-specification-schema.json
{
  "$id": "https://se.kivra.com/schemas/json/retail/ps/v1.0",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "prescription specification schema",
  "type": "object",
  "properties": {
    "business_unit": {
      "description": "Merchant information",
      "$ref": "business-definitions.json#/definitions/business_information"
    },
    "cashier": {
      "description": "Identifies the person handling the purchase if applicable",
      "$ref": "sales-recording-system-definitions.json#/definitions/cashier"
    },
    "receipt_identifier": {
      "description": "Receipt identifiers: sequence number and/or extended number with or without barcode representation",
      "$ref": "sales-recording-system-definitions.json#/definitions/receipt_identifier"
    },
    "time_of_purchase": {
      "description": "ISO 8601 date/time format: YYYY-MM-DDThh:mm:ssTZD",
      "type": "string",
      "format": "date-time"
    },
    "currency": {
      "description": "The receipt default currency. This gives the currency for all amounts in the receipt. If applicable overriding currencies can be added to the tender parts",
      "$ref": "monetary-definitions.json#/definitions/currency_code"
    },
    "amount_with_benefit": {
      "type": "number",
      "minimum":0
    },
    "amount_without_benefit": {
      "type": "number",
      "minimum":0
    },
    "amount_paid_by_benefit": {
      "type": "number",
      "minimum":0
    },    
    "amount_to_pay": {
      "type": "number",
      "minimum":0
    },
    "customer": {
      "description": "The person or animal owner to whom the prescription is issued.",
      "anyOf": [
        {
          "$ref": "customer-definitions.json#/definitions/customer_identifier"
        },
        {
          "$ref": "customer-definitions.json#/definitions/customer_information"
        }
      ]
    },
    "animal": {
      "$ref": "prescription-specification-definitions.json#/definitions/animal_related"
    },
    "human": {
      "$ref": "prescription-specification-definitions.json#/definitions/human_related"
    },
    "medications": {
      "type": "array",
      "description": "medications etc, connected to this pre. spec",
      "items": {
        "$ref": "prescription-specification-definitions.json#/definitions/prescription_item"
      }
    },    
    "expedition": {
      "type": "object",
      "properties": {
        "id": {
          "description": "expedition id, prescription id, etc",
          "type": "string"          
        },
        "details": {
          "description": "this is what the user will see",
          "type": "array",
          "minItems": 1,
          "items": {
           "type": "string"
          }
        }
      },
      "required": [
        "id",
        "details"
      ]
    },
    "additionalProperties": false
  },
  "oneOf": [
    {
      "required": [
        "animal"
      ]
    },
    {
      "required": [
        "human", "amount_with_benefit"
      ]
    }
  ],
  "allOf": [
    {
      "required": [
        "business_unit"
      ]
    },
    {
      "required": [
        "cashier"
      ]
    },
    {
      "required": [
        "receipt_identifier"
      ]
    },
    {
      "required": [
        "time_of_purchase"
      ]
    },
    {
      "required": [
        "amount_without_benefit"
      ]
    },
    {
      "required": [
        "amount_to_pay"
      ]
    },
    {
      "required": [
        "expedition"
      ]
    }
  ],
  "additionalProperties": false
}

=== kivra/developer.kivra.com/receipt/wiki/receipt-doc/prescription/example-prescription-specs/human-prescription-1.json
{
  "business_unit": {
    "contact": {
      "address": {
        "locality": "City",
        "postal_code": "123 45",
        "street_address": "Östra storgatan 6",
        "type": {
          "type": "business"
        }
      },
      "email": "info@ta.se",
      "phone": "0123456789"
    },
    "name": "Test apoteket",
    "organization_number": "112233-4455",
    "service_id": "16399966934684ed5d5d534373b33ef89846460b06",
    "unit_id": "5"
  },
  "cashier": {
    "id": "T02SUIT"
  },
  "receipt_identifier": {
    "sequence_number": 123456,
    "extended_number": {
      "value": "0123456123",
      "type": "EAN8",
      "context": "store"
    }
  },
  "time_of_purchase": "2023-03-27T08:49:00+01:00",
  "customer": {
    "id": {
      "birth_date": "19900805"
    },
    "name": "Knapp, Lena"
  },
  "expedition": {
    "id": "T02 AAN631",
    "details": ["Inköp på expedition T02 AAN631"]
  },
  "human": {
    "high_cost": {
      "previous_period": {
        "gross": 8982.64,
        "net": 2350.0,
        "start_date": "2021-07-12T08:00:00+02:00"
      },
      "current_period": {
        "gross": 28198.71,
        "net": 2400.0,
        "start_date": "2022-08-12T08:00:00+02:00"
      },
      "next_period": {
        "gross": 0.0,
        "net": 0.0,
        "start_date": "2023-08-13T08:00:00+02:00"
      },
      "amount_left_to_reimbursement": {
        "gross": 100.00,
        "net": 100.00
      }
    }
  },
  "amount_with_benefit": 58.27,
  "amount_without_benefit": 5.38,
  "amount_paid_by_benefit": 58.27,
  "amount_to_pay": 5.38
}

=== kivra/developer.kivra.com/receipt/wiki/receipt-doc/prescription/example-prescription-specs/human-prescription-2.json
{
  "business_unit": {
    "contact": {
      "address": {
        "locality": "City",
        "postal_code": "23456",
        "street_address": "Västra storgatan 99",
        "type": {
          "type": "business"
        }
      },
      "email": "info@ata.se",
      "phone": "0123456788"
    },
    "name": "Another test apotek",
    "organization_number": "112233-4466",
    "service_id": "16399966934684ed5d5d534373b33ef89846460b07",
    "unit_id": "ata-01"
  },
  "cashier": {
    "id": "01CSR"
  },
  "receipt_identifier": {
    "sequence_number": 29547,
    "extended_number": {
      "value": "029547123",
      "type": "EAN8",
      "context": "chain"
    }
  },
  "time_of_purchase": "2015-04-21T16:30:00+02:00",
  "customer": {
    "id": {
      "civic_registration_number": "199008051234"
    },
    "name": "Knapp, Lena"
  },
  "expedition": {
    "id": "154789798A",
    "details": [
      "Inköp på recept 154789798A",
      "Läkare Kinhult Anna-Carin",
      "Läkare Winsö Katarina"
    ]
  },
  "human": {
    "high_cost": {
      "previous_period": {
        "gross": 0.0,
        "net": 0.0,
        "start_date": "2014-02-14T08:00:00+02:00"
      },
      "current_period": {
        "gross": 2116.80,
        "net": 2116.80,
        "start_date": "2015-02-14T08:00:00+02:00"
      },
      "next_period": {
        "gross": 0.0,
        "net": 0.0,
        "start_date": "2016-02-14T08:00:00+02:00"
      }
    }
  },
  "amount_with_benefit": 0.0,
  "amount_without_benefit": 1929.80,
  "amount_paid_by_benefit":0.0,
  "amount_to_pay": 1929.80
  
}
