=== kivra/developer.kivra.com/receipt/schemas/json/retail/v1.0/digital-receipt-schema.json
{
  "$id": "https://se.digitalreceipts.net/schemas/json/retail/v1.0",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "description": "digital receipt schema",

  "type": "object",
  "properties": {
    "copy": {
      "type": "boolean",
      "default": false,
      "description": "If true the receipt is a copy"
    },
    "business_unit": {
      "description": "Merchant information",
      "$ref": "business-definitions.json#/definitions/business_information"
    },
    "cashier": {
      "description": "Identifies the person handling the purchase if applicable",
      "$ref": "sales-recording-system-definitions.json#/definitions/cashier"
    },
    "sales_recording_system": {
      "description": "Information about the point of sales system used. The system producing the receipt",
      "$ref": "sales-recording-system-definitions.json#/definitions/sales_recording_system"
    },
    "receipt_identifier": {
      "description": "Receipt identifiers: sequence number and/or extended number with or without barcode representation",
      "$ref": "sales-recording-system-definitions.json#/definitions/receipt_identifier"
    },
    "time_of_purchase": {
      "description": "ISO 8601 date/time format: YYYY-MM-DDThh:mm:ssTZD",
      "type": "string",
      "format": "date-time"
    },
    "currency": {
      "description": "The receipt default currency. This gives the currency for all amounts in the receipt. If applicable overriding currencies can be added to the tender parts",
      "$ref": "monetary-definitions.json#/definitions/currency_code"
    },
    "totals": {
      "description": "Total amounts and types, example net, gross, vat, discount",
      "type": "array",
      "items": {
        "oneOf": [{
            "$ref": "monetary-definitions.json#/definitions/total_discount_element"
          },
          {
              "$ref": "monetary-definitions.json#/definitions/total_paid_element"
            },
          {
              "$ref": "monetary-definitions.json#/definitions/total_gross_element"
          },
          {
            "$ref": "monetary-definitions.json#/definitions/total_tax_element"
          },
          {
            "$ref": "monetary-definitions.json#/definitions/total_loyalty_element"
          },
          {
            "$ref": "monetary-definitions.json#/definitions/total_net_rounding_element"
          }

        ]
      }
    },

    "header_text": {
      "description": "Any textual information aimed for the receipt header",
      "$ref": "service-common-definitions.json#/definitions/text_arr"
    },
    "footer_text": {
      "description": "Any textual information aimed for the receipt footer",
      "$ref": "service-common-definitions.json#/definitions/text_arr"
    },

    "items": {
      "description": "List of receipt items, goods or services sold/returned",
      "type": "array",
      "items": {
        "oneOf": [{
            "$ref": "item-definitions.json#/definitions/sale_item"
          },
          {
            "$ref": "item-definitions.json#/definitions/return_item"
          },
          {
            "$ref": "item-definitions.json#/definitions/text_item"
          },
          {
            "$ref": "item-definitions.json#/definitions/deposit_item"
          }
        ]
      }
    },

    "retail_price_modifiers": {
      "type": "array",
      "description": "Specifies any modifier(s) related to the amount paid by the customer. Example: 5% discount on the total amount",
      "items": {
        "$ref": "monetary-definitions.json#/definitions/retail_price_modifier_general"
      }
    },

    "payments": {
      "description": "Tender related information, several tender types can be used for payment",
      "type": "array",
      "items": {
        "$ref": "tender-definitions.json#/definitions/tender_element"
      }
    },

    "customer": {
      "description": "Information and/or identification of the customer",
      "anyOf": [{
          "$ref": "customer-definitions.json#/definitions/customer_identifier"
        },
        {
          "$ref": "customer-definitions.json#/definitions/customer_information"
        }
      ]
    },
    "customer_order": {
      "description": "Information about a connected customer order if applicable",
      "$ref": "customer-order-definitions.json#/definitions/customer_order_information"
    },

    "control_unit": {
      "description": "Control unit information required by swedish tax authorities",
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "code": {
          "type": "string"
        }
      },
      "required": ["id"]
    }
  },
  "required": ["business_unit", "sales_recording_system", "receipt_identifier", "time_of_purchase", "currency", "totals", "items", "payments"],
  "additionalProperties": false
}

=== kivra/developer.kivra.com/receipt/schemas/json/retail/v1.0/receipts/min-sale-receipt-cash-payment.json
{
    "business_unit": {
        "service_id": "15594097555922f97bfeb148d6b9a6ef76f76ebdce",
        "organization_number": "556838-8200",
        "name": "Findity store AB",
        "contact": {
            "address": {
                "street_address": "Engelbrektsgatan 20",
                "locality": "Ludvika",
                "postal_code": "77187"
            },
            "phone": "+460771584886"
        }
    },

    "cashier": {
        "id": "5",
        "name": "Anna Andersson"
    },
    "sales_recording_system": {
        "serial_number": "EA38329",
        "name": "kassa 3"
    },
    "receipt_identifier": {
        "sequence_number": 123456,
        "extended_number": {
            "value": "0123456123",
            "type": "EAN8",
            "context": "store"
        }
    },
    "time_of_purchase": "2018-11-09T08:49:00+01:00",
    "currency": "SEK",

    "totals": [
        {
            "type": "net",
            "amount": 280.0,
            "refund": false
        },
        {
            "type": "vat",
            "amount": 70.0,
            "refund": false,
            "sub_totals": [
                {
                    "amount": 70.0,
                    "taxable_amount": 350.0,
                    "net_amount": 280.00,
                    "tax_percentage": 25
                }
            ]
        },
        {
            "type": "gross",
            "amount": 395.0,
            "refund": false
        },
        {
            "type": "discount",
            "amount": 45.0
        },
        {
            "type": "rounding",
            "amount": 0.0
        },
        {
            "type": "paid",
            "amount": 350.0,
            "refund": false
        }
    ],

    "header_text": {
        "type": "array",
        "collection": ["Öppettider: Mådag - Fredag 10-18 Lördag 10-15", "Another header text..."]
    },
    "footer_text": {
        "type": "array",
        "collection": ["Sommarerbjudande: Köp 3 par skor få det billigaste paret på köpet."]
    },

    "items": [
        {
            "type": "sale",
            "identifiers": [
                {
                    "identifier_type": "pos",
                    "value": "912042"
                },
                {
                    "identifier_type": "gtin",
                    "value": "1234567890"
                }
            ],
            "description": "Skor 42 - Foder BR",
            "quantity": {
                "value": 1,
                "unit": "ea"
            },
            "regular_sales_unit_price": 395,
            "extended_gross_amount": 395,
            "retail_price_modifiers": [
                {
                    "amount": 45
                }
            ],
            "actual_sales_unit_price": 350,
            "extended_amount": 350,
            "tax_percentage": 25,
            "sequence_number": 1
        }
    ],

    "payments": [
        {
            "tender": {
                "type": "cash"
            },
            "amount_applied_to_bill": 350.0,
            "amount": 350.0
        }
    ],

    "customer": {
        "id": {
            "phone": "+46 75 777 7777"
        }
    },

    "control_unit": {
        "id": "RIHTT102710007088",
        "code": "BGXOV2QOHHILXHLPHHXRAYZEKGFNC2BD;"
    }
}

=== kivra/developer.kivra.com/receipt/schemas/json/retail/v1.0/receipts/min-return-receipt-cash-payment.json
{
    "business_unit": {
        "service_id": "15594097555922f97bfeb148d6b9a6ef76f76ebdce",
        "organization_number": "556838-8200",
        "name": "Findity store AB",
        "contact": {
            "address": {
                "street_address": "Engelbrektsgatan 20",
                "locality": "Ludvika",
                "postal_code": "77187"
            },
            "phone": "+460771584886"
        }
    },

    "cashier": {
        "id": "5",
        "name": "Anna Andersson"
    },
    "sales_recording_system": {
        "serial_number": "EA38329",
        "name": "kassa 3"
    },
    "receipt_identifier": {
        "sequence_number": 123457
    },
    "time_of_purchase": "2018-12-09T11:19:00+01:00",
    "currency": "SEK",

    "totals": [
        { "type": "net", "amount": 280.0, "refund": true },
        {
            "type": "vat",
            "amount": 70.0,
            "refund": true,
            "sub_totals": [
                {
                    "amount": 70.0,
                    "taxable_amount": 280.0,
                    "net_amount": 210.00,
                    "refund": true,
                    "tax_percentage": 25
                }
            ]
        },
        { "type": "gross", "amount": 395.0, "refund": true },
        { "type": "discount", "amount": 45.0, "refund": false },
        { "type": "rounding", "amount": 0.0 },
        { "type": "paid", "amount": 350.0, "refund": true }
    ],

    "header_text": {
        "type": "array",
        "collection": ["Öppettider: Mådag - Fredag 10-18 Lördag 10-15", "Another header text..."]
    },

    "items": [
        {
            "type": "return",
            "identifiers": [
                { "identifier_type": "pos", "value": "912042" },
                { "identifier_type": "gtin", "value": "1234567890" }
            ],
            "description": "Skor 42 - Foder BR",
            "quantity": {
                "value": 1,
                "entry_method": "scanned",
                "unit": "ea"
            },
            "regular_sales_unit_price": 395,
            "retail_price_modifiers": [
                {
                    "amount": 45
                }
            ],
            "actual_sales_unit_price": 350,
            "extended_amount": 350,
            "extended_gross_amount": 350,
            "tax_percentage": 25,
            "sequence_number": 1,
            "receipt_reference": {
                "value": "0123456123",
                "context": "store"
            }
        }
    ],

    "payments": [
        {
            "tender": {
                "type": "cash"
            },
            "amount_applied_to_bill": 350.0,
            "amount": 350.0,
            "refund": true
        }
    ],

    "customer": {
        "id": {
            "phone": "+46 75 777 7777"
        }
    },

    "control_unit": {
        "id": "RIHTT102710007088",
        "code": "BGXOV2QOHHILXHLPHHXRAYZEKGFNC2BD;"
    }
}

=== kivra/developer.kivra.com/receipt/schemas/json/retail/v1.0/receipts/min-sale-receipt-cash-payment-deposit.json
{
  "business_unit": {
    "service_id": "15594097555922f97bfeb148d6b9a6ef76f76ebdce",
    "organization_number": "556838-8200",
    "name": "Findity store AB",
    "contact": {
      "address": {
        "street_address": "Engelbrektsgatan 20",
        "locality": "Ludvika",
        "postal_code": "77187"
      },
      "phone": "+460771584886"
    }
  },

  "cashier": {
    "id": "5",
    "name": "Anna Andersson"
  },
  "sales_recording_system": {
    "serial_number": "EA38329",
    "name": "kassa 3"
  },
  "receipt_identifier": {
    "sequence_number": 123456,
    "extended_number": {
      "value": "0123456123",
      "type": "EAN8",
      "context": "store"
    }

  },
  "time_of_purchase": "2018-11-09T08:49:00+01:00",
  "currency": "SEK",

  "totals": [{
      "type": "net",
      "amount": 14.36
    },
    {
      "type": "vat",
      "amount": 7.64,
      "sub_totals": [{
        "amount": 7.64,
        "taxable_amount": 22.00,
        "net_amount": 39.00,
        "tax_percentage": 12
      }]
    },
    {
      "type": "gross",
      "amount": 22.00
    },
    {
      "type": "rounding",
      "amount": 0.00
    },
    {
      "type": "paid",
      "amount": 22.00
    }
  ],

  "header_text": {
    "type": "array",
    "collection": [
      "Öppettider: Mådag - Fredag 10-18 Lördag 10-15",
      "Another header text..."
    ]
  },
  "items": [{
    "type": "sale",
    "identifiers": [{
        "identifier_type": "pos",
        "value": "912042"
      }
    ],
    "description": "Mumsig läskedryck",
    "quantity": {
      "value": 1,
      "unit": "ea"
    },
    "regular_sales_unit_price": 20.00,
    "actual_sales_unit_price": 20.00,
    "extended_amount": 20.00,
    "extended_gross_amount": 20.00,
    "tax_percentage": 12,
    "sequence_number": 1
  },
  {
    "type": "deposit",
    "amount": 2.00,
    "unit_amount": 2.00,
    "quantity": 1,
    "refund": false,
    "sequence_number": 2,
    "item_link": 1,
    "text": {
        "type": "array",
        "collection": [
        "Pant Mumsig läskedryck"
      ]
      }
  }],

  "payments": [{
    "tender": {
      "type": "cash"
    },
    "amount_applied_to_bill": 22.00,
    "amount": 22.00
  }],

  "customer": {
    "id": {
      "phone": "+46 75 777 7777"
    }
  },

  "control_unit": {
    "id": "RIHTT102710007088",
    "code": "BGXOV2QOHHILXHLPHHXRAYZEKGFNC2BD;"
  }
}

=== kivra/developer.kivra.com/receipt/schemas/json/retail/v1.0/receipts/min-sale-receipt-cash-payment-rpm.json
{
  "business_unit": {
    "contact": {
      "address": {
        "locality": "Ludvika",
        "postal_code": "77187",
        "street_address": "Engelbrektsgatan 20"
      },
      "phone": "+460771584886"
    },
    "name": "Findity store AB",
    "organization_number": "556838-8200",
    "service_id": "15594097555922f97bfeb148d6b9a6ef76f76ebdce"
  },
  "cashier": {
    "id": "5",
    "name": "Anna Andersson"
  },
  "currency": "SEK",
  "items": [{
    "sequence_number": 1,
    "type": "sale",
    "identifiers": [{
      "value": "912040",
      "identifier_type": "pos"
    }],
    "quantity": {
      "value": 1,
      "unit": "l"
    },
    "tax_percentage": 12.00,
    "description": "Mumsig läskedryck svart",
    "extended_amount": 20.00,
    "extended_gross_amount": 20.00,
    "regular_sales_unit_price": 20.00,
    "eligible_for_frequent_shopper_points": true,
    "actual_sales_unit_price": 20.00
  }, {
    "sequence_number": 2,
    "type": "deposit",
    "amount": 2.00,
    "unit_amount": 2.00,
    "quantity": 1,
    "refund": false,
    "item_link": 1
  }, {
    "sequence_number": 3,
    "type": "sale",
    "identifiers": [{
      "value": "912041",
      "identifier_type": "pos"
    }],
    "quantity": {
      "value": 1,
      "unit": "l"
    },
    "tax_percentage": 12.00,
    "description": "Mumsig läskedryck röd",
    "extended_amount": 20.00,
    "extended_gross_amount": 20.00,
    "regular_sales_unit_price": 20.00,
    "eligible_for_frequent_shopper_points": true,
    "actual_sales_unit_price": 20.00
  }, {
    "sequence_number": 4,
    "type": "deposit",
    "amount": 2.00,
    "unit_amount": 2.00,
    "quantity": 1,
    "refund": false,
    "item_link": 3
  }, {
    "sequence_number": 5,
    "type": "sale",
    "identifiers": [{
      "value": "912042",
      "identifier_type": "pos"
    }],
    "quantity": {
      "value": 1,
      "unit": "l"
    },
    "tax_percentage": 12.00,
    "description": "Mumsig läskedryck orange",
    "extended_amount": 20.00,
    "extended_gross_amount": 20.00,
    "regular_sales_unit_price": 20.00,
    "eligible_for_frequent_shopper_points": true,
    "actual_sales_unit_price": 20.00
  }, {
    "sequence_number": 6,
    "type": "deposit",
    "amount": 2.00,
    "unit_amount": 2.00,
    "quantity": 1,
    "refund": false,
    "item_link": 5
  }],
  "payments": [{
    "amount": 50.00,
    "amount_applied_to_bill": 46.00,
    "tender": {
      "type": "cash"
    }
  }, {
    "amount": 4.00,
    "amount_applied_to_bill": 4.00,
    "refund": true,
    "tender": {
      "type": "cash"
    }
  }],
  "receipt_identifier": {
    "extended_number": {
      "value": "0123456123",
      "type": "EAN8",
      "context": "store"
    },
    "sequence_number": 123456
  },
  "sales_recording_system": {
    "serial_number": "EA38329",
    "name": "kassa 3"
  },
  "header_text": {
    "type": "array",
    "collection": ["Öppettider: Mådag - Fredag 10-18", "Lördag 10-15"]
  },
  "time_of_purchase": "2018-11-09T08:49:00+01:00",
  "totals": [{
    "amount": 41.00,
    "type": "net",
    "refund": false
  }, {
    "amount": 7.00,
    "type": "vat",
    "refund": false,
    "sub_totals": [{
      "amount": 7,
      "tax_percentage": 12.00,
      "taxable_amount": 46.00,
      "net_amount": 39.00,
      "refund": false
    }]
  }, {
    "amount": 66.00,
    "type": "gross",
    "refund": false,
    "sub_totals": [{
      "amount": 60,
      "points": 20,
      "type": "eligible_for_frequent_shopper_points",
      "text": {
        "type": "array",
        "collection": ["Bonusgrundande belopp"]
      },
      "refund": false
    }]
  }, {
    "amount": 0.00,
    "type": "rounding",
    "refund": false
  }, {
    "amount": 46.00,
    "type": "paid",
    "refund": false,
    "sub_totals": [{
      "amount": 50,
      "type": "received",
      "text": {
        "type": "array",
        "collection": ["Mottaget"]
      }
    }, {
      "amount": 4,
      "type": "returned",
      "text": {
        "type": "array",
        "collection": ["Växel"]
      }
    }]
  }, {
    "amount": 20.00,
    "type": "discount",
    "refund": true
  }],
  "customer": {
    "id": {
      "phone": "+46 75 777 7777"
    },
    "loyalty": {
      "program": "stammis",
      "customer_number": "1111222233334444",
      "incremental_count": 20,
      "current_count": 100000,
      "target_count": 150000
    }
  },
  "control_unit": {
    "code": "BGXOV2QOHHILXHLPHHXRAYZEKGFNC2BD;",
    "id": "RIHTT102710007088"
  },
  "retail_price_modifiers": [{
    "action": "subtract",
    "amount": 20.00,
    "description": {
      "type": "array",
      "collection": ["3 läsk betala för 2"]
    },
    "item_links": [1, 3, 5]
  }]
}

=== kivra/developer.kivra.com/receipt/schemas/json/retail/v1.0/receipts/min-sale-receipt-foreign-currency-payment.json
{
  "business_unit": {
    "service_id": "15594097555922f97bfeb148d6b9a6ef76f76ebdce",
    "organization_number": "556838-8200",
    "name": "Findity store AB",
    "contact": {
      "address": {
        "street_address": "Engelbrektsgatan 20",
        "locality": "Ludvika",
        "postal_code": "77187"
      },
      "phone": "+460771584886"
    }
  },

  "cashier": {
    "id": "5",
    "name": "Anna Andersson"
  },
  "sales_recording_system": {
    "serial_number": "EA38329",
    "name": "kassa 3"
  },
  "receipt_identifier": {
    "sequence_number": 123456,
    "extended_number": {
      "value": "0123456123",
      "type": "EAN8",
      "context": "store"
    }

  },
  "time_of_purchase": "2018-11-09T08:49:00+01:00",
  "currency": "SEK",

  "totals": [{
      "type": "net",
      "amount": 280.00
    },
    {
      "type": "vat",
      "amount": 70.00,
      "sub_totals": [{
        "amount": 70.00,
        "taxable_amount": 350.00,
        "net_amount": 280.00,
        "tax_percentage": 25
      }]
    },
    {
      "type": "gross",
      "amount": 395.00
    },
    {
      "type": "discount",
      "amount": 45.00
    },
    {
      "type": "rounding",
      "amount": 0.00
    },
    {
      "type": "paid",
      "amount": 350.00
    }
  ],

  "header_text": {
    "type": "array",
    "collection": [
      "Öppettider: Mådag - Fredag 10-18 Lördag 10-15",
      "Another header text..."
    ]
  },
  "footer_text": {
    "type": "array",
    "collection": [
      "Sommarerbjudande: Köp 3 par skor få det billigaste paret på köpet."
    ]
  },

  "items": [{
    "type": "sale",
    "entry_method": "scanned",
    "identifiers": [{
        "identifier_type": "pos",
        "value": "912042"
      },
      {
        "identifier_type": "gtin",
        "value": "1234567890"
      }
    ],
    "description": "Skor 42 - Foder BR",
    "quantity": {
      "value": 1,
      "unit": "ea"
    },
    "regular_sales_unit_price": 395,
    "retail_price_modifiers": [{
      "amount": 45,
      "action": "subtract",
      "description": {
          "type": "array",
          "collection": ["Rabatt på alla skor"]
      }
    }],
    "actual_sales_unit_price": 350,
    "extended_amount": 350,
    "extended_gross_amount": 350,
    "tax_percentage": 25,
    "sequence_number": 1
  }],

  "retail_price_modifiers": [{
    "amount": 35.00,
    "percent": 10,
    "description": {
        "type": "array",
        "collection": ["10% of, todays special"]
    }
  }],

  "payments": [{
    "tender": {
      "type": "cash"
    },
    "amount_applied_to_bill": 315.00,
    "amount": 315.00,
    "foreign_currency_amount": {
      "currency": "EUR",
      "original_face_amount": 30.08,
      "exchange_rate": 10.4728
    }
  }],

  "customer": {
    "id": {
      "phone": "+46 75 777 7777"
    }
  },

  "control_unit": {
    "id": "RIHTT102710007088",
    "code": "BGXOV2QOHHILXHLPHHXRAYZEKGFNC2BD;"
  }
}

=== kivra/developer.kivra.com/receipt/wiki/receipt-doc/retail/example-receipts/sale-receipt-card-payment.json
{
  "business_unit": {
    "service_id": "15594097552e6dfbe7ca6d4679acd8120c3344cc8c",
    "organization_number": "123456-1111",
    "name": "Sample Store BB",
    "contact": {
      "address": {
        "street_address": "Sparakvittotgatan 20",
        "locality": "Ludvika",
        "postal_code": "77100"
      },
      "phone": "+46-0771-584886"
    }
  },

  "cashier": {
    "name": "Mika"
  },
  "sales_recording_system": {
    "name": "Kassa 1"
  },

  "receipt_identifier": {
    "sequence_number": 144079,
    "extended_number": {
      "value": "0144079",
      "type": "Interleaved2Of5",
      "context": "chain"
    }
  },
  "time_of_purchase": "2018-11-09T11:07:00+01:00",
  "currency": "SEK",
  "totals": [{
      "type": "net",
      "amount": 390.40
    },
    {
      "type": "vat",
      "amount": 97.60,
      "sub_totals": [{
        "amount": 97.60,
        "tax_percentage": 25,
        "taxable_amount": 390.40,
        "net_amount": 292.80
      }]
    },
    {
      "type": "gross",
      "amount": 488.00
    },
    {
      "type": "paid",
      "amount": 488.00
    }
  ],
  "footer_text": {
    "type": "array",
    "collection": [
      "För reavaror gäller byte i 5 dagar.",
      "Bad- & underkläder bytes endast plomberade.",
      "Välkommen åter"
    ]
  },
  "items": [{
      "type": "sale",
      "identifiers": [{
        "identifier_type": "pos",
        "value": "000077-284305 45025-L"
      }],
      "description": "Short Shorts, 3xSport",
      "quantity": {
        "value": 1,
        "unit": "ea"
      },
      "regular_sales_unit_price": 279.00,
      "actual_sales_unit_price": 195.30,
      "extended_amount": 195.30,
      "extended_gross_amount": 279.00,
      "retail_price_modifiers": [{
        "amount": 83.70
      }],
      "tax_percentage": 25,
      "sequence_number": 1
    },
    {
      "type": "sale",
      "identifiers": [{
        "identifier_type": "pos",
        "value": "000007-084205 01031-L"
      }],
      "description": "Short shorts, 2 to go",
      "quantity": {
        "value": 2,
        "unit": "ea"
      },
      "regular_sales_unit_price": 209.00,
      "actual_sales_unit_price": 146.35,
      "extended_amount": 292.70,
      "extended_gross_amount": 418.00,
      "retail_price_modifiers": [{
        "amount": 62.65
      }],
      "extended_discount_amount": 125.30,
      "tax_percentage": 25,
      "sequence_number": 2
    }
  ],
  "payments": [{
    "tender": {
      "type": "creditdebit",
      "card_token": {
        "value": "123455",
        "scheme": "payment_provider_scheme"
      },
      "payment_slip": {
        "type": "array",
        "collection": [
          "BB Ludvika Ou",
          "Sparakvittotgatan 20",
          "S-77100 LUDVIKA",
          "TEL +46-0771-584886",
          "Org.nr: 123456-1111",
          "Teller Sweden AB",
          "Butiksnr: 10565281",
          "Termid: 7320080100029574",
          "2018-11-09 11:22",
          "KÖP",
          "SEK: 488,00",
          "Varav moms: 139,40",
          "TOTALT: 488-00",
          "Personlig kod",
          "**** **** **** 3602",
          "",
          "Bankkort VISA",
          "Ca2 1 ___ TEL 315 L99029",
          "Ref.nr: 000295749077",
          "AID: A000000003101000",
          "TVR: 0000000000",
          "TSI: E800",
          "SPARA KVITTOT",
          "KUNDENS KOPIA",
          "",
          "Transaktionsinformation",
          "Butiksnr: 58213559",
          "          4368122",
          "Term.id: 7320080100029574",
          "2018-11-09 11:22",
          "              KÖP",
          "BELOPP: SEK187,00",
          "",
          "GODKÄNT",
          "************8796",
          "Bankkort VISA",
          "Personlig kod",
          "Ca1 7 000 SWE 415 826244",
          "Ref.nr: 301005397477",
          "AID A00000000041010",
          "2018-11-09         09:49",
          "TSI E800",
          "TVR 0080001000",
          "SemportNr: 4196"
        ]
      }
    },
    "amount": 488.00,
    "amount_applied_to_bill": 488.00
  }],
  "customer": {
    "id": {
      "civic_registration_number": "19990909-1999"
    }
  },
  "control_unit": {
    "id": "RIHTT102710007088"
  }
}
