=== kivra/developer.kivra.com/receipt/schemas/json/retail/v1.0/digital-receipt-schema.json
{
  "$id": "https://se.digitalreceipts.net/schemas/json/retail/v1.0",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "description": "digital receipt schema",

  "type": "object",
  "properties": {
    "copy": {
      "type": "boolean",
      "default": false,
      "description": "If true the receipt is a copy"
    },
    "business_unit": {
      "description": "Merchant information",
      "$ref": "business-definitions.json#/definitions/business_information"
    },
    "cashier": {
      "description": "Identifies the person handling the purchase if applicable",
      "$ref": "sales-recording-system-definitions.json#/definitions/cashier"
    },
    "sales_recording_system": {
      "description": "Information about the point of sales system used. The system producing the receipt",
      "$ref": "sales-recording-system-definitions.json#/definitions/sales_recording_system"
    },
    "receipt_identifier": {
      "description": "Receipt identifiers: sequence number and/or extended number with or without barcode representation",
      "$ref": "sales-recording-system-definitions.json#/definitions/receipt_identifier"
    },
    "time_of_purchase": {
      "description": "ISO 8601 date/time format: YYYY-MM-DDThh:mm:ssTZD",
      "type": "string",
      "format": "date-time"
    },
    "currency": {
      "description": "The receipt default currency. This gives the currency for all amounts in the receipt. If applicable overriding currencies can be added to the tender parts",
      "$ref": "monetary-definitions.json#/definitions/currency_code"
    },
    "totals": {
      "description": "Total amounts and types, example net, gross, vat, discount",
      "type": "array",
      "items": {
        "oneOf": [{
            "$ref": "monetary-definitions.json#/definitions/total_discount_element"
          },
          {
              "$ref": "monetary-definitions.json#/definitions/total_paid_element"
            },
          {
              "$ref": "monetary-definitions.json#/definitions/total_gross_element"
          },
          {
            "$ref": "monetary-definitions.json#/definitions/total_tax_element"
          },
          {
            "$ref": "monetary-definitions.json#/definitions/total_loyalty_element"
          },
          {
            "$ref": "monetary-definitions.json#/definitions/total_net_rounding_element"
          }

        ]
      }
    },

    "header_text": {
      "description": "Any textual information aimed for the receipt header",
      "$ref": "service-common-definitions.json#/definitions/text_arr"
    },
    "footer_text": {
      "description": "Any textual information aimed for the receipt footer",
      "$ref": "service-common-definitions.json#/definitions/text_arr"
    },

    "items": {
      "description": "List of receipt items, goods or services sold/returned",
      "type": "array",
      "items": {
        "oneOf": [{
            "$ref": "item-definitions.json#/definitions/sale_item"
          },
          {
            "$ref": "item-definitions.json#/definitions/return_item"
          },
          {
            "$ref": "item-definitions.json#/definitions/text_item"
          },
          {
            "$ref": "item-definitions.json#/definitions/deposit_item"
          }
        ]
      }
    },

    "retail_price_modifiers": {
      "type": "array",
      "description": "Specifies any modifier(s) related to the amount paid by the customer. Example: 5% discount on the total amount",
      "items": {
        "$ref": "monetary-definitions.json#/definitions/retail_price_modifier_general"
      }
    },

    "payments": {
      "description": "Tender related information, several tender types can be used for payment",
      "type": "array",
      "items": {
        "$ref": "tender-definitions.json#/definitions/tender_element"
      }
    },

    "customer": {
      "description": "Information and/or identification of the customer",
      "anyOf": [{
          "$ref": "customer-definitions.json#/definitions/customer_identifier"
        },
        {
          "$ref": "customer-definitions.json#/definitions/customer_information"
        }
      ]
    },
    "customer_order": {
      "description": "Information about a connected customer order if applicable",
      "$ref": "customer-order-definitions.json#/definitions/customer_order_information"
    },

    "control_unit": {
      "description": "Control unit information required by swedish tax authorities",
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "code": {
          "type": "string"
        }
      },
      "required": ["id"]
    }
  },
  "required": ["business_unit", "sales_recording_system", "receipt_identifier", "time_of_purchase", "currency", "totals", "items", "payments"],
  "additionalProperties": false
}

=== kivra/developer.kivra.com/receipt/wiki/receipt-doc/retail/example-receipts/min-sale-receipt-cash-payment-rpm.json
{
  "business_unit": {
    "service_id": "15594097555922f97bfeb148d6b9a6ef76f76ebdce",
    "organization_number": "556838-8200",
    "name": "Findity store AB",
    "contact": {
      "address": {
        "street_address": "Engelbrektsgatan 20",
        "locality": "Ludvika",
        "postal_code": "77187"
      },
      "phone": "+460771584886"
    }
  },

  "cashier": {
    "id": "5",
    "name": "Anna Andersson"
  },
  "sales_recording_system": {
    "serial_number": "EA38329",
    "name": "kassa 3"
  },
  "receipt_identifier": {
    "sequence_number": 123456,
    "extended_number": {
      "value": "0123456123",
      "type": "EAN8",
      "context": "store"
    }

  },
  "time_of_purchase": "2018-11-09T08:49:00+01:00",
  "currency": "SEK",

  "totals": [{
      "type": "net",
      "amount": 41.00,
      "refund": false
    },
    {
      "type": "vat",
      "amount": 7.00,
      "refund": false,
      "sub_totals": [{
        "amount": 7.00,
        "taxable_amount": 46.00,
        "net_amount": 39.00,
        "tax_percentage": 12,
        "refund": false
      }]
    },
    {
      "type": "gross",
      "amount": 66.00,
      "refund": false,
      "sub_totals": [{
        "type": "eligible_for_frequent_shopper_points",
        "amount": 60.00,
        "points": 20,
        "refund": false,
        "text": {
          "type": "array",
          "collection": ["Bonusgrundande belopp"]
        }
      }]
    },
    {
      "type": "rounding",
      "amount": 0.00
    },
    {
      "type": "paid",
      "amount": 46.00,
      "refund": false,
      "sub_totals": [{
          "type": "received",
          "amount": 50.00,
          "text": {
            "type": "array",
            "collection": ["Mottaget"]
          }
        },
        {
          "type": "returned",
          "amount": 4.00,
          "text": {
            "type": "array",
            "collection": ["Växel"]
          }
        }
      ]
    },
    {
      "type": "discount",
      "amount": 20.00,
      "refund": true,
      "sub_totals": [{
        "amount": 13.00,
        "refund": true,
        "type": "loyalty"
      }]
    }
  ],

  "header_text": {
    "type": "array",
    "collection": [
      "Öppettider: Mådag - Fredag 10-18",
      "Lördag 10-15"
    ]
  },
  "items": [{
      "type": "sale",
      "identifiers": [{
        "identifier_type": "pos",
        "value": "912040"
      }],
      "description": "Mumsig läskedryck svart",
      "quantity": {
        "value": 1,
        "unit": "l"
      },
      "eligible_for_frequent_shopper_points": true,
      "actual_sales_unit_price": 20.00,
      "extended_amount": 20.00,
      "regular_sales_unit_price": 20.00,
      "extended_gross_amount": 20.00,
      "tax_percentage": 12,
      "sequence_number": 1
    },
    {
      "type": "deposit",
      "amount": 2.00,
      "unit_amount": 2.00,
      "quantity": 1,
      "refund": false,
      "sequence_number": 2,
      "item_link": 1
    },
    {
      "type": "sale",
      "identifiers": [{
        "identifier_type": "pos",
        "value": "912041"
      }],
      "description": "Mumsig läskedryck röd",
      "quantity": {
        "value": 1,
        "unit": "l"
      },
      "eligible_for_frequent_shopper_points": true,
      "actual_sales_unit_price": 20.00,
      "extended_amount": 20.00,
      "regular_sales_unit_price": 20.00,
      "extended_gross_amount": 20.00,
      "tax_percentage": 12,
      "sequence_number": 3
    },
    {
      "type": "deposit",
      "amount": 2.00,
      "unit_amount": 2.00,
      "quantity": 1,
      "refund": false,
      "sequence_number": 4,
      "item_link": 3
    },
    {
      "type": "sale",
      "identifiers": [{
        "identifier_type": "pos",
        "value": "912042"
      }],
      "description": "Mumsig läskedryck orange",
      "quantity": {
        "value": 1,
        "unit": "l"
      },
      "eligible_for_frequent_shopper_points": true,
      "actual_sales_unit_price": 20.00,
      "extended_amount": 20.00,
      "regular_sales_unit_price": 20.00,
      "extended_gross_amount": 20.00,
      "tax_percentage": 12,
      "sequence_number": 5
    },
    {
      "type": "deposit",
      "amount": 2.00,
      "unit_amount": 2.00,
      "quantity": 1,
      "refund": false,
      "sequence_number": 6,
      "item_link": 5
    }
  ],

  "retail_price_modifiers": [{
    "amount": 20.00,
    "action": "subtract",
    "description": {
      "type": "array",
      "collection": ["3 läsk betala för 2"]
    },
    "item_links": [
      1, 3, 5
    ]
  }],

  "payments": [{
    "tender": {
      "type": "cash"
    },
    "refund": false,
    "amount_applied_to_bill": 46.00,
    "amount": 50.00
  }, {
    "tender": {
      "type": "cash"
    },
    "refund": true,
    "amount_applied_to_bill": 4.00,
    "amount": 4.00
  }],

  "customer": {
    "id": {
      "phone": "+46 75 777 7777"
    }
  },

  "control_unit": {
    "id": "RIHTT102710007088",
    "code": "BGXOV2QOHHILXHLPHHXRAYZEKGFNC2BD;"
  }
}

=== kivra/developer.kivra.com/receipt/schemas/json/retail/v1.0/receipts/sale-voucher-payment.json
{
  "business_unit": {
    "contact": {
      "address": {
        "country_name": "Sverige",
        "locality": "Köpstad",
        "postal_code": "11100",
        "street_address": "Stortorget 278"
      },
      "phone": "46771584886"
    },
    "name": "My Superstore",
    "organization_number": "1122334444",
    "service_id": "15594097555922f97bfeb148d6b9a6ef76f76ebdce"
  },
  "cashier": {
    "id": "Olle"
  },
  "control_unit": {
    "code": "66262",
    "id": "RIHTT103801065896"
  },
  "currency": "SEK",
  "customer": {
    "id": {
      "civic_registration_number": "192210228884"
    }
  },
  "items": [{
      "sequence_number": 1,
      "type": "sale",
      "identifiers": [{
          "value": "608794",
          "identifier_type": "pos"
        },
        {
          "value": "010300",
          "identifier_type": "pos",
          "identifier_sub_type": "mainGroup",
          "identifier_qualifier": "bil-mc"
        },
        {
          "value": "010303",
          "identifier_type": "pos",
          "identifier_sub_type": "articleGroup",
          "identifier_qualifier": "säkerhetsdetaljer"
        }
      ],
      "quantity": {
        "value": 1,
        "unit": "ea",
        "entry_method": "scanned"
      },
      "tax_percentage": 25,
      "description": "Bogserlina med krokar",
      "extended_amount": 138,
      "extended_gross_amount": 148,
      "regular_sales_unit_price": 79,
      "retail_price_modifiers": [{
          "action": "subtract",
          "amount": 10.0
        },
        {
          "action": "add",
          "amount": 10.0,
          "description": {
            "type": "array",
            "collection": ["custom fee"]
          }
        }
      ],
      "actual_sales_unit_price": 69
    },
    {
      "sequence_number": 2,
      "type": "sale",
      "identifiers": [{
          "value": "923048",
          "identifier_type": "pos"
        },
        {
          "value": "070700",
          "identifier_type": "pos",
          "identifier_sub_type": "mainGroup",
          "identifier_qualifier": "kontor-teknik"
        },
        {
          "value": "0870773",
          "identifier_type": "pos",
          "identifier_sub_type": "articleGroup",
          "identifier_qualifier": "hörlurar"
        }
      ],
      "quantity": {
        "value": 1,
        "unit": "ea",
        "entry_method": "scanned"
      },
      "tax_percentage": 25,
      "description": "Headset hörlurar - SLR",
      "extended_amount": 49,
      "extended_gross_amount": 49,
      "regular_sales_unit_price": 49,
      "actual_sales_unit_price": 49
    },
    {
      "sequence_number": 3,
      "type": "sale",
      "identifiers": [{
          "value": "912042",
          "identifier_type": "pos"
        },
        {
          "value": "020100",
          "identifier_type": "pos",
          "identifier_sub_type": "mainGroup",
          "identifier_qualifier": "verktyg"
        },
        {
          "value": "020101",
          "identifier_type": "pos",
          "identifier_sub_type": "articleGroup",
          "identifier_qualifier": "skor-stövlar"
        }
      ],
      "quantity": {
        "value": 1,
        "unit": "ea",
        "entry_method": "scanned"
      },
      "tax_percentage": 25,
      "description": "Stövel 42 - Fodrad BR",
      "extended_amount": 395,
      "extended_gross_amount": 395,
      "regular_sales_unit_price": 395,
      "actual_sales_unit_price": 395
    },
    {
      "sequence_number": 4,
      "type": "sale",
      "identifiers": [{
          "value": "608003",
          "identifier_type": "pos"
        },
        {
          "value": "040000",
          "identifier_type": "pos",
          "identifier_sub_type": "mainGroup",
          "identifier_qualifier": "hem"
        },
        {
          "value": "040003",
          "identifier_type": "pos",
          "identifier_sub_type": "articleGroup",
          "identifier_qualifier": "övrigt"
        }
      ],
      "quantity": {
        "value": 1,
        "unit": "ea",
        "entry_method": "scanned"
      },
      "tax_percentage": 25,
      "description": "Plastpåse",
      "extended_amount": 1.5,
      "extended_gross_amount": 1.5,
      "regular_sales_unit_price": 0,
      "actual_sales_unit_price": 1.5
    }
  ],
  "payments": [{
      "amount": 503,
      "amount_applied_to_bill": 503,
      "tender": {
        "type": "giftcard",
        "card_number": "xxxxxxx1234",
        "expiration_date": "2012-12-31",
        "current_balance": 503
      }
    },
    {
      "amount": 488,
      "amount_applied_to_bill": 488,
      "tender": {
        "type": "voucher",
        "tender_details": {
          "type": "array",
          "collection": [
            "Voucher TypeCode: AdvancePayment",
            "Description: Some voucher description",
            "FaceValueAmount Currency: SEK",
            "FaceValueAmount: 500.00",
            "SerialNumber: v-1234-001",
            "ExpirationDate: 2018-11-09",
            "UnspentAmount: 500.00",
            "VoucherAmountInChange: 100.00",
            "IssuingStoreNumberID TypeCode: Distributor",
            "IssuingStoreNumberID: 123"
          ]
        }
      }
    },
    {
      "amount": 55.5,
      "amount_applied_to_bill": 55,
      "rounding": 0.5,
      "tender": {
        "type": "cash"
      }
    },
    {
      "amount": 55.5,
      "amount_applied_to_bill": 55,
      "rounding": 0.5,
      "tender": {
        "type": "house_account"
      }
    }
  ],
  "receipt_identifier": {
    "extended_number": {
      "value": "02890093672714",
      "type": "Interleaved2Of5",
      "context": "store"
    },
    "sequence_number": 123789798712300
  },
  "sales_recording_system": {
    "serial_number": "EA38329",
    "id": "65252"
  },
  "header_text": {
    "type": "array",
    "collection": [
      "Öppettider: Måndag - Fredag 10-18, Lördag 10-15"
    ]
  },
  "footer_text": {
    "type": "array",
    "collection": [
      "Spara kvittot, gäller som garanti.",
      "Öppet köp 30 dagar."
    ]
  },
  "time_of_purchase": "2017-12-02T11:49:00+01:00",
  "totals": [{
      "amount": 11,
      "type": "discount",
      "sub_totals": [{
          "amount": 10,
          "text": {
            "type": "array",
            "collection": [
              "Ngn form av rabatt"
            ]
          }
        },
        {
          "amount": 1,
          "text": {
            "type": "array",
            "collection": [
              "En krona rabatt på allt"
            ]
          }
        }
      ]
    },
    {
      "amount": 112.7,
      "type": "vat",
      "sub_totals": [{
          "amount": 111.7,
          "tax_percentage": 25,
          "taxable_amount": 446.8,
          "net_amount": 349.30
        },
        {
          "amount": 1,
          "tax_percentage": 10,
          "taxable_amount": 10,
          "net_amount": 9
        }
      ]
    },
    {
      "amount": 558.5,
      "type": "net"
    },
    {
      "amount": 558,
      "type": "paid"
    }
  ]
}

=== kivra/developer.kivra.com/receipt/schemas/json/retail/v1.0/receipts/sale-receipt-tender-type-other-with-barcode.json
{
  "business_unit": {
    "service_id": "15594097552e6dfbe7ca6d4679acd8120c3344cc8c",
    "organization_number": "123456-1111",
    "name": "Sample Store BB",
    "contact": {
      "address": {
        "street_address": "Sparakvittotgatan 20",
        "locality": "Ludvika",
        "postal_code": "77100"
      },
      "phone": "+46-0771-584886"
    }
  },

  "cashier": {
    "name": "Mika"
  },
  "sales_recording_system": {
    "name": "Kassa 1"
  },

  "receipt_identifier": {
    "sequence_number": 144079,
    "extended_number": {
      "value": "0144079",
      "type": "Interleaved2Of5",
      "context": "chain"
    }
  },
  "time_of_purchase": "2018-11-09T11:07:00+01:00",
  "currency": "SEK",
  "totals": [{
      "type": "net",
      "amount": 390.40
    },
    {
      "type": "vat",
      "amount": 97.60,
      "sub_totals": [{
        "amount": 97.60,
        "tax_percentage": 25,
        "taxable_amount": 390.40,
        "net_amount": 292.80
      }]
    },
    {
      "type": "gross",
      "amount": 488.00
    },
    {
      "type": "paid",
      "amount": 488.00
    }
  ],
  "footer_text": {
    "type": "array",
    "collection": [
      "För reavaror gäller byte i 5 dagar.",
      "Bad- & underkläder bytes endast plomberade.",
      "Välkommen åter"
    ]
  },
  "items": [{
      "type": "sale",
      "identifiers": [{
        "identifier_type": "pos",
        "value": "000077-284305 45025-L"
      }],
      "description": "Short Shorts, 3xSport",
      "quantity": {
        "value": 1,
        "unit": "ea"
      },
      "regular_sales_unit_price": 279.00,
      "actual_sales_unit_price": 195.30,
      "extended_amount": 195.30,
      "extended_gross_amount": 279.00,
      "retail_price_modifiers": [{
        "amount": 83.70
      }],
      "tax_percentage": 25,
      "sequence_number": 1
    },
    {
      "type": "sale",
      "identifiers": [{
        "identifier_type": "pos",
        "value": "000007-084205 01031-L"
      }],
      "description": "Short shorts, 2 to go",
      "quantity": {
        "value": 2,
        "unit": "ea"
      },
      "regular_sales_unit_price": 209.00,
      "actual_sales_unit_price": 146.35,
      "extended_amount": 292.70,
      "extended_gross_amount": 418.00,
      "retail_price_modifiers": [{
        "amount": 62.65
      }],
      "extended_discount_amount": 125.30,
      "tax_percentage": 25,
      "sequence_number": 2
    }
  ],
  "payments": [{
    "tender": {
      "type": "other",
      "type_name": "KLARNA",
      "tender_details": {
        "type": "array",
        "collection": [
          "Butiksnr:  8708",
          "Fakturanr: 2260 6633 2099 9960",
          "Kund Idnr: 12334454545"
        ],
        "barcode": {
          "value": "$EPAY${\"Butiknr\": \"8708\",\"Faktnr\": \"2260663320999960\"}",
          "type": "QRCode"
        }
      }
    },
    "amount": 488.00,
    "amount_applied_to_bill": 488.00
  }],
  "customer": {
    "id": {
      "civic_registration_number": "19990909-1999"
    }
  },
  "control_unit": {
    "id": "RIHTT102710007088"
  }
}
